### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by GaryK4** [IAsDoubleYou/homeassistant-mysql_query#3]
It appears that this HACS only supports one database configuration.yaml and the automation. I have data from multiple databases on the same server. It would be helpful if SELECT database,table would work. Or mysql_db: DB could be added as a qualifier in the automation.

**Comment by IAsDoubleYou** [comment]
@GaryK4 thanks for raising this feature request. 
I can see how it will add to the usability of the component.

Approach for implementation:
1. The database configured with the mysql_db configuration parameter will act as the default database for each query
2. When invoking the service, a new parameter DB4QUERY will be available to override the default database for this query

With this approach, the component will be compatible with the previous version, while providing a way to use multiple databases.

Example:
```text
service: mysql_query.query
data:
  query: select "hello world" from dual
  db4query: contact
```

**Comment by GaryK4** [comment]
That sounds like a good solution!
