### ISSUE TITLE
Database setup to use different port

### ISSUE THREAD

**Issue by Tiki-24** [IAsDoubleYou/homeassistant-mysql_query#8]
I had problems getting this to work on a database I setup on a QNAP NAS, I finally figured out that it was down to the the NAS assigning a port of 3307 rather than the standard 3306.  I did a bit of playing and updated the const.py to include port with the following:-

CONF_MYSQL_PORT = "mysql_port"

DEFAULT_MYSQL_PORT = 3306

then included this in the main py file to read the value and include port in the connector, with the default option and then a different port can be set in the configuration.yaml if needed

**Comment by IAsDoubleYou** [comment]
Hi @Tiki-24,

Thanks for your feedback and suggestion to improve the component.
I have adjusted the code to reflect your suggestion and will build and release it soon.
Please feel free to review the code, it has already been commited to the main branch.

**Comment by IAsDoubleYou** [comment]
Releasing in version 1.2.0
