### ISSUE TITLE
SQL WITH Clause & Storing JSON Response into Input Text Helper

### ISSUE THREAD

**Issue by royf007** [IAsDoubleYou/homeassistant-mysql_query#9]
First of all, this is a fantastic integration.  Thank you for writing it!!

I'm using it to pull energy usage statistics for a given date range.  

I wrote a complex query in my automation using the SQL **WITH** clause against MariaDB.  It always returns an empty response.

The query runs fine directly on the database.  Below is an example of this type of query (this simple example shows the issue). The "response" is always empty though.

```
description: >-
  Test SQL With Clause
mode: single
trigger:
  - platform: state
    entity_id:
      - input_button.run_energy_cost_report_button
condition: []
action:
  - service: mysql_query.query
    data:
      query: |
        WITH ABC AS (SELECT 'Hello' FROM DUAL)
        SELECT * FROM ABC
    response_variable: response
  - service: input_text.set_value
    data:
      value: |
        {{ response }}
    target:
      entity_id: input_text.sql_result
```

I'm not sure if this is a bug?  I've since re-written my query to use a sub-select, instead of the **WITH** clause.

On another note.... I don't think the next issue is an integration bug, but maybe the way Home Assistant works.  For testing, I'm trying to set the same input text helper, called **input_text.sql_result**, (configured for a max of 3000 characters) with the result of a query, and the **set_value** service is not storing the result in the input text helper.

I'm not sure if Home Assistant can't handle the length, newlines, special characters, etc.  Below is the SQL response JSON I'm trying to set, which is returned from my query:

```
{'result': [{'date': datetime.date(2024, 5, 29), 'datetime_local':
datetime.datetime(2024, 5, 29, 22, 0, 10, 354330), 'latest_created_ts':
1717038010.3387063, 'statistics_id': 17, 'stat_id_name':
'sensor.4244_consumed_energy_kwh_cost', 'total_sum': 0.41204799999999797,
'mean': None, 'min': None, 'max': None, 'last_reset': None,
'last_reset_ts': 1717032229.294907, 'state': 0.263755999999998, 'sum':
0.41204799999999797}, {'date': datetime.date(2024, 5, 30),
'datetime_local': datetime.datetime(2024, 5, 30, 0, 0, 10, 346312),
'latest_created_ts': 1717041610.3463125, 'statistics_id': 1197,
'stat_id_name': 'sensor.consumed_energy_kwh_cost', 'total_sum':
1.421792, 'mean': None, 'min': None, 'max': None, 'last_reset': None,
'last_reset_ts': 1717032229.294907, 'state': 1.2735, 'sum': 1.421792}]}
```

I would think that any text can be stored as long as it doesn't exceed the size limit?

**Comment by IAsDoubleYou** [comment]
Hi royf007,

Thank you for your supportive feedback!

The description of the issue is clear. At the moment i have no clue, why the ‘with’ clause is not working with the component.
I will have a look at it asap and ket you know. Have you already checked the logfile to see if there is any indication of the cause?

Regarding the **set_value** function, i don’t know if there are restrictions for the string value. Have you already tried to set a value that contains a similar literal value from the developers tools. Also you might check the logfile and see if there are error messages that might be of any help.
If i can free up some time i will also play with it and see if i can find out why it doesn’t store the json result.

I’ll keep you updated.

**Comment by IAsDoubleYou** [comment]
Found the reason why the WITH clause is not working.
I had a restriction in the code so that the query should always start with SELECT. Since the purpose of this component is readonly i did that to prevent INSERTs, UPDATEs and DELETEs.

Now WITH is also a valid keyword which the query may start with.
I'll build and release the fixed component soon.

**Comment by IAsDoubleYou** [comment]
Issue regarding CTE queries ('WITH' clause) has been fixed and releases in version v1.2.1

**Comment by royf007** [comment]
Hi @IAsDoubleYou , thank you so much for the quick turnaround and code fix for the "with" clause issue.  Hopefully you got enough sleep! I've just tested the new release and it's working great.

For the other issue I mentioned, the **set_value**  function, it looks like I'm hitting the 255 character limit for HA state values, which I'm just learning about.  I am able to get a large JSON payload from the SQL query and iterate through it or email the entire response, so no issue with your integration there.

My use case is that I want to render an HTML table from the query results.  So I was looking for a way to store the JSON response from the query in some type of entity, and then use that in the UI. It seems that HA does not have the 255 character limit on an entity's attribute values, but HA doesn't make it easy to set attribute values.  Some solutions that I've seen but haven't tried yet is to create an MQTT sensor and publish the the JSON SQL response to it.

Have you seen any examples where someone is rendering the SQL response in a Lovelace card?

**Comment by IAsDoubleYou** [comment]
Hi @royf007, i'm glad to hear that the fix works for you and thanks for confirming.
Don't worry i'm getting some sleep anyhow 😄 

Regarding the **set_value**, i understand the 255 character limit for states and also what you're trying to achieve.
I don't have not seen examples where someone is rendering a large string in Lovelace.

However i have been working on a MySQL sensor component sometime ago. It's basically working, but i have to spent some time to complete it. It wasn't high priority so i haven't worked on it for some months now.

The sensor will store every field of teh first record of a query as an attribute of the entity. The state will hold the number of records found.
I tried a query that returns a literal string of 700 characters and was able to render the result in a Markdown Lovelace card without any problem.

So to go short:
1. You could try to render your JSON SQL response in a Markdown Lovelace card.
2. I will spent some time on my new custom component that will support passing query results of the first record as entity attributes. Do you think that could be of any help for your use case?

**Comment by royf007** [comment]
Hi @IAsDoubleYou , thank you! Yes, it would definitely help my use case to have the query results loaded into a sensor / attributes.  I've been playing around with an MQTT sensor in the meantime, and I was able to manually publish a JSON payload as follows:

`{"state":"2", "json_sql_response":[{"date":"2024-05-29","total":0.263755999999998,"sum":0.41204799999999797},{"date":"2024-05-30","total":1.2735,"sum":1.421792}]}`

Note, the built-in Home Assistant MQTT sensor is very picky about JSON.  It will fail if there are any newlines.  It needs to be terse.

This is what it looks like in Developer Tools:

![image](https://github.com/IAsDoubleYou/homeassistant-mysql_query/assets/4976402/e6b60b3e-2932-40ec-a28f-b9a1c3aef4e5)

I've set the state value to the number of records returned, but don't see why more than 1 attribute would be needed in the custom sensor to store the JSON response.  I haven't researched it yet, but maybe Home Assistant allows array type objects in a sensor attribute value that isn't necessarily JSON?  If so, the array of results could be stored.

Having the custom component to populate a sensor / attributes from the query results would avoid the whole MQTT sensor.

When you say "passing query results of the first record as entity attributes", would you still be able to support multiple SQL return rows? I'm not saying to create a new attribute for each SQL row returned, but even a JSON array of records would work.  I'm showing an example of this in my JSON above.

The other thing that I noticed with the current integration, when I send the response object to my GMail, is that it's not proper JSON, and doesn't match what is returned from the database.

My query results from a DB client are:

![image](https://github.com/IAsDoubleYou/homeassistant-mysql_query/assets/4976402/2d3dead8-6091-497f-9800-30880bdeb326)

The integration response object I'm getting is:

`[{'date': datetime.date(2024, 5, 29), 'total': 0.263755999999998, 'sum': 0.41204799999999797}, {'date': datetime.date(2024, 5, 30), 'total': 1.2735, 'sum': 1.421792}]` which is not valid JSON.

When you are building the response object, it seems to convert the date and date / time fields into their object representations.

The query I'm using is something like:

`SELECT DATE(FROM_UNIXTIME(s.created_ts)) AS DATE, FROM_UNIXTIME(s.created_ts) AS datetime_local ...`

From a JSON query response perspective, it would make sense that the date and datetime query results would be strings with quotes around them, and then any numeric values would not have quotes:

![image](https://github.com/IAsDoubleYou/homeassistant-mysql_query/assets/4976402/c374e57e-e85a-408d-bac6-f9138b72ef25)

Please let me know if you need any more info, but I definitely look forward to your custom component, and appreciate your work.

**Comment by IAsDoubleYou** [comment]
Thanks for the information.

It's not clear to me which SQL sensor component you are currently using that provides your sample output.
The **mysql_query** is not a sensor component but only provides a service that returns a python result set (not in JSON format) which has to be iterated to collect every record.

The other component that i was referring to is one that i'm currently developing, which i currently named **HA MySQL**
This component will execute a given query and return the record count in the entity's state.
Only the first record of the resultset will be used to populate attributes of the sensor.
Every field of the first record will be an attribute of the sensor.

## For example:

>select field1, field2, field3 from table
the values of field1, field2, field3 will be available as 3 different attributes and can be used in a Lovelace card.

1. Currently i have not planned to use the values of following records to populate the sensor. But i could add a service to the component to fetch the next record so the sensor will be refreshed with the values of the next record.
2. I'm not sure if you have a requirement to that the result should be in JSON format. If so i'm curious why, could you please explain a bit further?
3. I could try to fetch all the records of the resultset and return them as a JSON array, but that might cause problems since the resultset could be very large, depending on the query and the content of the database.

**Comment by royf007** [comment]
Ah ok.  So, I am not using any SQL sensor component for this sample output.  This is what I am proposing as the JSON format that is returned from the **mysql_query** in the response, which then can be stored in a sensor's attributes.  I am able to "store" the result currently with the MQTT Sensor, providing that it is in the the correct JSON format from the **mysql_query** integration.  I can also try to convert the python result set from **mysql_query** to JSON in order to use the MQTT sensor.

The only reason that I'm focused on JSON is that currently it's the only way I know to store the result in a sensor's attribute.  I can also write the SQL result to a file, and then use that file to build the UI table.

So, ultimately, I'm trying to render an HTML or markup table in a Lovelace card, where the rows and columns of the table come from a SQL query.  It looks like the maximum size that can be stored in a sensor's attribute is 16384 bytes.  And, yes, there is a potential for a very large payload.  

I'm just not sure how else do build this.

**Comment by IAsDoubleYou** [comment]
Ok, i understand it now.
First i have to say that i will not be able to change the output format of the **mysql_query** into JSON, since this will break the component for current users.
I will see if there's a possibility to also return the complete query result in my new component in JSON format an make it available as an attribute of the sensor.
But if the max size is 16384, then i may have to truncate the result if it's lsize exceeds that limit.
So then it will be the users responsibility to build the query in such way that it will fit.

I'm not sure if i can build it that way, but i'm willing to try.

I'll keep you updated.

**Comment by royf007** [comment]
Thank you! That makes sense.  Adding another component with the JSON results would be awesome.

**Comment by IAsDoubleYou** [comment]
Hi @royf007,

i've picked up the development of my new **HA MySQL** sensor component and making some progress.
I would appreciate some feedback from your side.

Below is a fragment from the **JSON result** attribute displayed in a **Markdown Lovelace card**

<img width="468" alt="image" src="https://github.com/IAsDoubleYou/homeassistant-mysql_query/assets/21007864/51d2c153-a1a2-4665-8c4e-2277d73586a3">
<br/><br/>

## Dynamic attributes
As explained before, the sensor dynamically creates attributes for all fields that are SELECTed. These attributes reflects 1 record at a time. 
I'm planning to add some services which will allow to navigate trough the resultset which will be reflected by updated attributes values. 

## Static JSONResult attribute 
Besides the dynamic attributes, i've now also added a more static attribute that holds the complete resultset in JSON format.

In the current version of the component i'm returning a formatted JSON string with a fix indentation of 2 positions. The string also contains newline characters to produce "pretty format".
In case the string exceeds the max allowed size i will have to truncate it to make it fit. Of course this will break the JSON format so the string will become an invalid JSON string.

## Advise needed
Where i need some advise has to do with the eventual formatting of the JSON string. It's still not completely clear to me, why you would want to display a JSON string in the HA dashboard. So i'm not sure if you would like the JSON string to be formatted or rather not. In the final version i might add an option which can then be used to specify whether the output should be formatted or not.

**Comment by royf007** [comment]
Hi @IAsDoubleYou ,

Glad that you picked up development again on your **HA MySQL Sensor**.  They Dynamic Attributes make sense for iterating over 1 record at-a-time.

Your formatted JSON sample for the static JSONResult attribute looks great.  The reason I mentioned in my previous post, that the JSON should have no newlines was solely for being able to set the JSON string into my MQTT sensor's attributes through the **MQTT Sensor** integration.  For example, this is my **configuration.yaml**

```
###########################################
### MQTT Sensors ##########################
###########################################

mqtt:
  sensor:
    - name: "SQL Results"
      state_topic: "homeassistant/sql"
      json_attributes_topic: "response"
      json_attributes_template: "{{ value_json }}"
```

When I publish an MQTT message with formatted JSON, the **MQTT Sensor** integration would not set the **SQL Results** entity's **json_attributes_topic** value.  When I publish a single line of JSON, this works.

If you are able to set the **static JSONResult attribute** with pretty formatted JSON in your integration and it works, then that is even better, as it's much more readable.

It's possible that it is only an issue with me using the **MQTT Sensor**. 

So, I'm not trying to display the JSON string directly on a Lovelace card, but rather, I was struggling to even store the JSON results to begin with.

Not really sure that you need to store 2 versions of JSON, as long as you can store it in the first place.  I would need to still iterate through the SQL results in the static JSONResult attribute to render a table in a Lovelace card.

Question: For the Dynamic Attributes, you mentioned that you plan to write some services to iterate through the records.  Does this mean you are still storing the whole result set in a persistent python object to iterate through when the service is called for each record, or does this mean you would need to keep the database connection open during iteration, or even issue a new query and go after the next row?  

I'm curious about the use case for the Dynamic Attributes and only storing the first record's results.  In a Jinja2 template, it's fairly easy to iterate through an array, including JSON arrays, especially if the entire result is already available in an entity's attribute.  How do you see the Dynamic Attributes being used....if a query is executed, would someone then use the data from first record, and then later go back and ask for the next record by calling a service?

**Comment by IAsDoubleYou** [comment]
Thank you for your feedback and explanation.

I am also working on the manual for the new component, which might help provide a better understanding of it.

Regarding persistence, in this version, the result is retained as an HA object. The connection to the database is closed in the meantime. If this setup causes issues in the future, such as memory usage, the strategy can always be changed.

As for the dynamic attributes, I designed them this way to present the data simply. 

**For example**: Let's say you want to retrieve the location of a person's entity (depending on the person's phone location) from the HA state database. The result will be stored in an "Location" attribute of the "sensor.person_location_query"  sensor. This can be presented in a Lovelace card.
To refresh the location value on the dashboard, you'll only need to re-execute the same query. This can be easily triggered from a button or automation.

Regarding the static JSONResult attribute, it contains the **complete result set**, including multiple records if applicable. You can then access the content yourself with a Jinja template to extract the desired information.

I think it will all become clearer once I publish the first (alpha) version of the component along with the draft of the manual. 

I have a busy weekend with family ahead, so I expect this to happen sometime next week.

**Comment by IAsDoubleYou** [comment]
First draft version of ha_mysql can be found here:

https://github.com/IAsDoubleYou/ha_mysql

Although it has to be brushed up, it should work.

**Comment by royf007** [comment]
Hi @IAsDoubleYou, thank you for publishing the Alpha version of this custom component!  I was doing some testing, and it's working great for me 😀.  A couple of observations / comments:

1. The supplied query needs to be on a single line.  So, when I tried using the multi-line YAML syntax, i.e.:
```
query: >- 
    WITH QUERY AS (
    SELECT 123 AS Number, 'Test String' AS Value
    )
    SELECT * FROM QUERY
```
  the query fails, so it needs to be written as:

```
 query: WITH QUERY AS (SELECT 123 AS Number, 'Test String' AS Value) SELECT * FROM QUERY
```

  That's not really an issue.  Maybe something to add to the docs.

2. The **json_result** is perfect for my needs and contains the entire query result
3. If 2 queries are executed, one after another using the same sensor, and the second one has no results, then the **json_results** attribute value is not cleared.
4. In addition to **query_date** and **query_time**, it would be great to have the **executed_sql_query** as another attribute of the sensor so the **json_results** can be correlated to which SQL query was actually run to produce the results.

If I think of anything else, I'll let you know.

**Comment by IAsDoubleYou** [comment]
Hi @royf007,

thank you so much for willing to test the component and the extensive feedback you’re providing. 
I”ll work on your suggestions soon and will keep you updated. 

To have everything in the right place for future reference I would request you to copy your last comment and enter it as an issue for the ha_mysql component itself. We can then further discuss it there 👍🏻

**Comment by IAsDoubleYou** [comment]
I've opened an issue for this topic here https://github.com/IAsDoubleYou/ha_mysql/issues/1 and will lock this conversation now.
Feedback over there will greatly be appreciated.
